#!/usr/bin/env python3
"""Generate an exact content identity for the backend Docker release context."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
from collections.abc import Iterable, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

RELEASE_PATHS = (
    Path("pyproject.toml"),
    Path("README.md"),
    Path("alembic.ini"),
    Path("packages"),
    Path("services"),
    Path("infra/migrations"),
    Path("config"),
    Path("data"),
    Path("scripts"),
)
IGNORED_DIRECTORY_NAMES = {
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "node_modules",
}
IGNORED_DATA_PREFIXES = (
    Path("data/raw"),
    Path("data/inbox"),
    Path("data/exports"),
)
IGNORED_SUFFIXES = (".pyc", ".pyo")


class ReleaseFingerprintError(RuntimeError):
    """Raised when an exact release identity cannot be produced."""


def collect_release_files(
    project_root: Path,
    include_paths: Sequence[Path] = RELEASE_PATHS,
) -> list[Path]:
    root = project_root.resolve()
    files: list[Path] = []
    for relative in include_paths:
        candidate = root / relative
        if not candidate.exists():
            raise ReleaseFingerprintError(f"release path does not exist: {relative}")
        candidates: Iterable[Path] = (candidate,) if candidate.is_file() else candidate.rglob("*")
        for path in candidates:
            relative_path = path.relative_to(root)
            if _is_ignored(relative_path) or path.is_dir():
                continue
            if path.is_symlink():
                raise ReleaseFingerprintError(f"release source contains a symlink: {relative_path}")
            if not path.is_file():
                raise ReleaseFingerprintError(
                    f"release source is not a regular file: {relative_path}"
                )
            files.append(relative_path)
    if not files:
        raise ReleaseFingerprintError("release source contains no files")
    return sorted(set(files), key=lambda value: value.as_posix())


def source_tree_hash(project_root: Path, files: Sequence[Path]) -> str:
    root = project_root.resolve()
    digest = hashlib.sha256(b"house-radar-release-v1\0")
    for relative_path in sorted(files, key=lambda value: value.as_posix()):
        digest.update(relative_path.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update((root / relative_path).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def git_commit(project_root: Path) -> str:
    try:
        value = subprocess.run(
            ("git", "rev-parse", "HEAD"),
            cwd=project_root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        value = os.environ.get("SHR_SOURCE_COMMIT", "").strip()
    if not value or value.lower() == "unknown":
        raise ReleaseFingerprintError(
            "git commit is unavailable; set SHR_SOURCE_COMMIT to the deployed revision"
        )
    return value


def release_tree_is_dirty(project_root: Path, include_paths: Sequence[Path]) -> bool:
    try:
        result = subprocess.run(
            (
                "git",
                "status",
                "--porcelain",
                "--untracked-files=all",
                "--",
                *(path.as_posix() for path in include_paths),
            ),
            cwd=project_root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return True
    return bool(result.stdout.strip())


def build_release_identity(
    project_root: Path,
    include_paths: Sequence[Path] = RELEASE_PATHS,
) -> dict[str, Any]:
    files = collect_release_files(project_root, include_paths)
    root = project_root.resolve()
    return {
        "schema_version": 1,
        "generated_at": datetime.now(UTC).isoformat(),
        "source_commit": git_commit(root),
        "source_tree_hash": source_tree_hash(root, files),
        "working_tree_dirty": release_tree_is_dirty(root, include_paths),
        "file_count": len(files),
        "total_bytes": sum((root / path).stat().st_size for path in files),
        "hash_algorithm": "sha256-path-and-content-v1",
    }


def write_env(path: Path, identity: dict[str, Any]) -> None:
    content = (
        "# Generated by scripts/release_fingerprint.py. Do not edit.\n"
        f"# working_tree_dirty={str(identity['working_tree_dirty']).lower()}\n"
        f"SHR_SOURCE_COMMIT={identity['source_commit']}\n"
        f"SHR_SOURCE_TREE_HASH={identity['source_tree_hash']}\n"
    )
    _atomic_write(path, content, mode=0o600)


def write_json(path: Path, identity: dict[str, Any]) -> None:
    _atomic_write(
        path,
        json.dumps(identity, ensure_ascii=False, indent=2) + "\n",
        mode=0o600,
    )


def _atomic_write(path: Path, content: str, *, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.chmod(mode)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def _is_ignored(relative_path: Path) -> bool:
    if any(part in IGNORED_DIRECTORY_NAMES for part in relative_path.parts):
        return True
    if relative_path.name == ".DS_Store" or relative_path.suffix in IGNORED_SUFFIXES:
        return True
    return any(
        relative_path == prefix or prefix in relative_path.parents
        for prefix in IGNORED_DATA_PREFIXES
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--write-env", type=Path)
    parser.add_argument("--write-json", type=Path)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    try:
        identity = build_release_identity(args.project_root)
        if args.write_env:
            write_env(args.write_env, identity)
        if args.write_json:
            write_json(args.write_json, identity)
    except (OSError, ReleaseFingerprintError) as exc:
        print(json.dumps({"status": "error", "error": str(exc)}))
        return 2
    print(json.dumps(identity, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
