from __future__ import annotations

from pathlib import Path

import pytest

from scripts import release_fingerprint


def test_tree_hash_is_deterministic_and_content_sensitive(tmp_path: Path) -> None:
    source = tmp_path / "source"
    source.mkdir()
    first = source / "b.py"
    second = source / "a.py"
    first.write_text("one\n", encoding="utf-8")
    second.write_text("two\n", encoding="utf-8")

    files = release_fingerprint.collect_release_files(tmp_path, (Path("source"),))
    initial = release_fingerprint.source_tree_hash(tmp_path, files)
    repeated = release_fingerprint.source_tree_hash(tmp_path, list(reversed(files)))
    second.write_text("changed\n", encoding="utf-8")
    changed = release_fingerprint.source_tree_hash(tmp_path, files)

    assert files == [Path("source/a.py"), Path("source/b.py")]
    assert repeated == initial
    assert changed != initial


def test_runtime_data_and_cache_files_are_excluded(tmp_path: Path) -> None:
    (tmp_path / "data/raw").mkdir(parents=True)
    (tmp_path / "data/inbox").mkdir()
    (tmp_path / "data/exports").mkdir()
    (tmp_path / "data/sample").mkdir()
    (tmp_path / "data/raw/feed.json").write_text("raw", encoding="utf-8")
    (tmp_path / "data/inbox/feed.csv").write_text("private", encoding="utf-8")
    (tmp_path / "data/exports/latest.json").write_text("runtime", encoding="utf-8")
    (tmp_path / "data/sample/example.json").write_text("sample", encoding="utf-8")
    (tmp_path / "data/sample/cache.pyc").write_bytes(b"cache")

    files = release_fingerprint.collect_release_files(tmp_path, (Path("data"),))

    assert files == [Path("data/sample/example.json")]


def test_symlinked_release_source_is_rejected(tmp_path: Path) -> None:
    source = tmp_path / "source"
    source.mkdir()
    target = tmp_path / "target.py"
    target.write_text("value\n", encoding="utf-8")
    (source / "linked.py").symlink_to(target)

    with pytest.raises(release_fingerprint.ReleaseFingerprintError, match="symlink"):
        release_fingerprint.collect_release_files(tmp_path, (Path("source"),))


def test_env_output_contains_only_release_identity(tmp_path: Path) -> None:
    output = tmp_path / ".env.release"
    identity = {
        "source_commit": "a" * 40,
        "source_tree_hash": "b" * 64,
        "working_tree_dirty": True,
    }

    release_fingerprint.write_env(output, identity)

    assert output.read_text(encoding="utf-8").splitlines() == [
        "# Generated by scripts/release_fingerprint.py. Do not edit.",
        "# working_tree_dirty=true",
        f"SHR_SOURCE_COMMIT={'a' * 40}",
        f"SHR_SOURCE_TREE_HASH={'b' * 64}",
    ]
